#SPDX-License-Identifier: GPL-2.0-only

ifneq ($(TARGET_DISABLE_HSI2S_DLKM),true)
ifeq ($(call is-board-platform-in-list,$(TARGET_BOARD_PLATFORM)),true)
    ifeq ($(ENABLE_HYP),true)
        BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/msm_hyp.ko
        BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/msm_hyp.ko
        BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/msm_hyp.ko

        BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/msm_cfg.ko
        BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/msm_cfg.ko
        BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/msm_cfg.ko
    else
        BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/msm_drm.ko
        BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/msm_drm.ko
        BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/msm_drm.ko
    endif
endif
endif # TARGET_DISABLE_HSI2S_DLKM
