# SPDX-License-Identifier: GPL-2.0-only

KDIR := $(TOP)/kernel_platform/msm-kernel

#ifeq (y, $(findstring y, $(CONFIG_QTI_QUIN_GVM)))
include $(DISPLAY_ROOT)/config/gvmdisp.conf
LINUXINCLUDE += -include $(DISPLAY_ROOT)/config/gvmdispconf.h
#endif

LINUX_INC +=    -Iinclude/linux \
        -Iinclude/linux/drm \

LINUX_INC +=	-I$(DISPLAY_ROOT) \
	-I$(DISPLAY_ROOT)/include \
	-I$(DISPLAY_ROOT)/include/linux \
	-I$(DISPLAY_ROOT)/msm-hyp \
	-I$(DISPLAY_ROOT)/msm \
	-I$(DISPLAY_ROOT)/msm-hyp/wfd \
	-I$(DISPLAY_ROOT)/msm-hyp/virtio \
	-I$(DISPLAY_ROOT)/include/uapi/display \

CDEFINES +=	-DANI_LITTLE_BYTE_ENDIAN \
	-DANI_LITTLE_BIT_ENDIAN \
	-DDOT11F_LITTLE_ENDIAN_HOST \
	-DANI_COMPILER_TYPE_GCC \
	-DANI_OS_TYPE_ANDROID=6 \
	-DPTT_SOCK_SVC_ENABLE \
	-Wall\
	-Werror\
	-D__linux__

KBUILD_CPPFLAGS += $(CDEFINES)

ccflags-y += $(LINUX_INC)

ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif

KBUILD_EXTRA_SYMBOLS +=$(OUT)/obj/vendor/qcom/opensource/display-drivers/hdcp/Module.symvers
KBUILD_EXTRA_SYMBOLS +=$(OUT)/obj/vendor/qcom/opensource/display-drivers/msm/Module.symvers

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif

ifneq ($(MODNAME), qdsp6v2)
CHIP_NAME ?= $(MODNAME)
CDEFINES += -DMULTI_IF_NAME=\"$(CHIP_NAME)\"
endif

######### CONFIG_MSM_HYP ########


ccflags-$(CONFIG_DRM_MSM_HYP) := -I$(KERNEL_ROOT)/include/drm \
             -I$(KERNEL_ROOT)/include/uapi/display \
             -I$(KERNEL_ROOT)/include \
             -I$(KERNEL_ROOT)/include/linux \
             -I$(DISPLAY_ROOT)/include/uapi/display \
             -I$(DISPLAY_ROOT)/include \
             -I$(DISPLAY_ROOT)/include/linux \
             -I$(DISPLAY_ROOT)/msm-hyp \
             -I$(DISPLAY_ROOT)/msm \

ccflags-$(CONFIG_DRM_MSM_HYP_WFD) += -I$(DISPLAY_ROOT)/msm-hyp/wfd
ccflags-$(CONFIG_DRM_MSM_HYP_VIRTIO) += -I$(DISPLAY_ROOT)/msm-hyp/virtio

CFLAGS_REMOVE_wfd/wfd_kms.o += -mgeneral-regs-only
CFLAGS_REMOVE_wfd/wire_user.o += -mgeneral-regs-only

msm_hyp-$(CONFIG_DRM_MSM_HYP) := \
			msm_hyp_trace_point.o \
			msm_drv_hyp.o\
			msm_hyp_notifier.o\
			msm_hyp_utils.o

msm_hyp-$(CONFIG_SYNC_FILE) += \
			msm_hyp_fence.o

msm_hyp-$(CONFIG_DRM_MSM_HYP_WFD) += \
			wfd/wfd_kms.o\
			wfd/user_hab_utils.o\
			wfd/wire_user.o

msm_hyp-$(CONFIG_DRM_MSM_HYP_VIRTIO) += \
			virtio/virtio_kms.o\
			virtio/virtgpu_vq.o

obj-$(CONFIG_DRM_MSM_HYP) += msm_hyp.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
